[DATABASE_17]
[DATABASE_17/TABLE_LISTAPRECOPRODUTO]
triggerName=C_listaPrecoEcommerce
triggerFiringTime=1
triggerActions=insert, update, delete
triggerPosition=0
[DATABASE_17/TABLE_ITEMESTOQUE]
triggerName=C_ITEMFILIAL
triggerFiringTime=0
triggerActions=insert, update
triggerPosition=0
[DATABASE_17/TABLE_MOVIMENTOESTOQUE]
triggerName=
triggerFiringTime=0
triggerActions=insert, update, delete
triggerPosition=0
[DATABASE_17/TABLE_C_DESTINOAVULSO]
triggerName=
triggerFiringTime=0
triggerActions=insert
triggerPosition=0
[DATABASE_13]
[DATABASE_13/TABLE_COMENTARIOS]
triggerName=
triggerFiringTime=0
triggerActions=insert
triggerPosition=0
[DATABASE_24]
[DATABASE_24/TABLE_NOTAFISCAL]
triggerName=pedidopendente
triggerFiringTime=1
triggerActions=insert, update
triggerPosition=0
[DATABASE_18]
[DATABASE_18/TABLE_C_FATURASPED]
triggerName=
triggerFiringTime=0
triggerActions=insert, update
triggerPosition=0
[DATABASE_18/TABLE_PEDIDO]
triggerName=
triggerFiringTime=0
triggerActions=insert, update
triggerPosition=0
[DATABASE_44]
[DATABASE_44/TABLE_MOVIMENTOESTOQUE]
triggerName=c_movEstqBloqueiaPedido
triggerFiringTime=0
triggerActions=insert
triggerPosition=100
[DATABASE_44/TABLE_C_FATORES]
triggerName=
triggerFiringTime=0
triggerActions=insert
triggerPosition=0
[DATABASE_67]
[DATABASE_67/TABLE_ACESSOS]
triggerName=
triggerFiringTime=0
triggerActions=insert, update, delete
triggerPosition=0
[DATABASE_69]
[DATABASE_69/TABLE_C_DESTINOAVULSO]
triggerName=
triggerFiringTime=0
triggerActions=insert
triggerPosition=0
